version: '3'

services:

    mongodb:
        image: mongo
        ports:
            - 27017:27017

    etl_sentiment:
        build: etl_sentiment/
        volumes:
            - ./etl_sentiment/src/:/app
            - ./logs/:/log
        depends_on:
            - mongodb
            - postgres

    slack_bot:
        build: slack_bot/
        volumes:
            - ./slack_bot/src/:/app
            - ./logs/:/log
        depends_on:
            - postgres

    tweet_collector:
        build: tweet_collector/

        volumes:
            - ./tweet_collector/src/:/app
            - ./logs/:/log
        depends_on:
            - mongodb

    postgres:
        image: postgres
        ports:
            - 5555:5432
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: etlpipe
            POSTGRES_DB: twitterdb

